use test69;
insert into site_update values(null, "12/12/12", 0, "this is udate one");
insert into site_update values(null, "13/13/13", 0, "this is udate two");
insert into site_update values(null, "14/14/14", 0, "this is udate three");
insert into site_update values(null, "15/15/15", 0, "this is udate four");
insert into site_update values(null, "16/16/16", 0, "this is udate five");
insert into site_update values(null, "17/17/16", 0, "this is udate six");
insert into site_update values(null, "18/18/16", 0, "this is udate seven");
insert into site_update values(null, "19/19/16", 0, "this is udate eight");
insert into site_update values(null, "20/20/16", 0, "this is udate nine");
insert into site_update values(null, "21/21/16", 0, "this is udate ten");
insert into site_update values(null, "22/22/16", 0, "this is udate eleven");
select * from site_update;